import { NameStyle } from "../types";

export interface RouteConfig {
  path: string;
  style: NameStyle;
  title: string;
  subtitle: string;
  description: string;
  emoji: string;
  navLabel: string;
  relatedTags: string[]; // Used for contextual blog linking
  seoContent: string; // Unique HTML content for the bottom of the landing page
  sampleNames: string[]; // Pre-rendered examples for SEO content depth
}

export const STYLE_ROUTES: Record<string, RouteConfig> = {
  [NameStyle.COOL]: {
    path: '/sweaty-roblox-names',
    style: NameStyle.COOL,
    navLabel: 'Sweaty PvP',
    emoji: '⚔️',
    title: "Sweaty Roblox Name Generator (2026) - Cool PvP Usernames",
    subtitle: "Tryhard, PvP & Edgy Usernames",
    description: "Generate sweaty, tryhard, and cool Roblox usernames instantly. Perfect for competitive players in BedWars, Da Hood, and Deepwoken who need a 'vIper' or 'Soul' style alias.",
    relatedTags: ['PvP', 'Sweaty', 'Security', 'Strategy'],
    sampleNames: ['NotViper', 'SoulSz', 'GrimFn', 'ToxicLegend', 'DarkEcho', 'NeonGhost', 'ViperXo', 'PureSkill', 'SilentAim', 'VoidWalker', 'RogueSz', 'EliteFn'],
    seoContent: `
      <h2>How to Create a "Sweaty" Roblox Username</h2>
      <p>In competitive games like <strong>Da Hood</strong>, <strong>BedWars</strong>, and <strong>Deepwoken</strong>, a "sweaty" username is a status symbol. It tells opponents that you are skilled, experienced, and dangerous. But what makes a name sweaty?</p>
      <ul>
        <li><strong>Minimalism:</strong> The best sweaty names are short. Use our generator to find 4-5 letter combinations. Avoid long strings like "DarkWarrior12345".</li>
        <li><strong>Clean Formatting:</strong> Avoid numbers if possible. Use suffixes like <strong>Fn</strong>, <strong>Sz</strong>, or <strong>Xo</strong> to make a taken word unique without ruining the aesthetic.</li>
        <li><strong>Mixed Capitalization:</strong> A hallmark of the PvP community. Names like <code>vIper</code> or <code>sOul</code> stand out on the leaderboard.</li>
      </ul>
      <h3>Top Sweaty Suffixes for 2026</h3>
      <p>If your desired keyword is taken, try appending these suffixes generated by our tool:</p>
      <ul>
        <li><strong>-Sz / -Szn:</strong> Implies "Season" or "Size". (e.g., <em>GrimSz</em>)</li>
        <li><strong>-Fn:</strong> A classic tag meaning "Fan" or implying competitive origins. (e.g., <em>ToxicFn</em>)</li>
        <li><strong>-Ly:</strong> Turns nouns into adverbs for a clean look. (e.g., <em>Richly</em>)</li>
      </ul>
    `
  },
  [NameStyle.AESTHETIC]: {
    path: '/aesthetic-roblox-usernames',
    style: NameStyle.AESTHETIC,
    navLabel: 'Aesthetic',
    emoji: '✨',
    title: "Aesthetic Roblox Username Generator (2026) - Soft & Y2K",
    subtitle: "Soft, Y2K & Cottagecore Ideas",
    description: "Create soft, dreamy, and aesthetic Roblox usernames. The best aesthetic name generator for cottagecore and y2k styles for Royale High and Brookhaven.",
    relatedTags: ['Aesthetic', 'Fashion', 'Display Names', 'Matching'],
    sampleNames: ['lunar.sky', 'soft.tea', 'pure.honey', 'dreamy.cloud', 'star.girl', 'angel.doll', 'vibes.xo', 'cloud.bby', 'y2k.fairy', 'cyber.heart', 'love.bug', 'silk.rose'],
    seoContent: `
      <h2>The Guide to Aesthetic Roblox Usernames</h2>
      <p>Whether you are dressing up in <strong>Royale High</strong>, hanging out in <strong>Berry Avenue</strong>, or creating a Y2K avatar, your name needs to match your vibe. Aesthetic usernames often prioritize lowercase letters, soft words, and unique spacing.</p>
      <h3>Popular Aesthetic Styles</h3>
      <ul>
        <li><strong>Soft / Cottagecore:</strong> Uses nature words like <em>honey</em>, <em>tea</em>, <em>cloud</em>, and <em>bun</em>. Often formatted in all lowercase (e.g., <code>cloud.tea</code>).</li>
        <li><strong>Y2K / Cyber:</strong> Focuses on retro-futurism. Keywords include <em>cyber</em>, <em>web</em>, <em>fairy</em>, and <em>bratz</em>.</li>
        <li><strong>Emo / Grunge:</strong> Darker aesthetics utilizing words like <em>void</em>, <em>numb</em>, and <em>broken</em>.</li>
      </ul>
      <h3>Using Display Names for Aesthetics</h3>
      <p>Remember, if your perfect aesthetic username is taken, you can use our generator to create a <strong>Display Name</strong>. Display names allow for special characters and spacing that standard usernames do not.</p>
    `
  },
  [NameStyle.OG]: {
    path: '/rare-og-roblox-names',
    style: NameStyle.OG,
    navLabel: 'Rare OG',
    emoji: '💎',
    title: "Rare OG Roblox Name Generator - Short 4 Letter Usernames",
    subtitle: "Short 4-Letter & Clean Usernames",
    description: "Generate rare-looking, short, and 'OG' style names. We use advanced algorithms to find clean combinations that look like they were created in 2010.",
    relatedTags: ['Rare Names', 'History', 'Strategy', 'Tips'],
    sampleNames: ['Kilo', 'Jinx', 'Void', 'Flux', 'Haze', 'Zeus', 'Echo', 'Nova', 'Rift', 'Apex', 'Zinc', 'Mace'],
    seoContent: `
      <h2>What is an "OG" Roblox Name?</h2>
      <p>An "OG" (Original Gangster) name refers to a username that looks like it was created in the early days of Roblox (2006-2010). These names are highly coveted for their rarity and simplicity.</p>
      <h3>Characteristics of a Rare Name</h3>
      <ul>
        <li><strong>Short Length:</strong> 3-character names are all taken, but 4-character and 5-character names are still the gold standard.</li>
        <li><strong>Real Words:</strong> Dictionary words (nouns/adjectives) without numbers.</li>
        <li><strong>No Special Characters:</strong> Pure letters, no underscores.</li>
      </ul>
      <h3>How to Find Available "OG" Names</h3>
      <p>While most dictionary words are gone, you can find "pseudo-OG" names by using our generator. We combine short prefixes (like <em>i</em>, <em>x</em>, <em>Not</em>) with short nouns to create names that feel rare (e.g., <em>NotGem</em>).</p>
    `
  },
  [NameStyle.CUTE]: {
    path: '/cute-roblox-names',
    style: NameStyle.CUTE,
    navLabel: 'Cute',
    emoji: '🌸',
    title: "Cute Roblox Username Generator - Kawaii Name Ideas",
    subtitle: "Kawaii, Pastel & Sweet Names",
    description: "Discover adorable and kawaii usernames inspired by anime, sweets, and nature. Perfect for players who want a charming and friendly identity.",
    relatedTags: ['Cute', 'Aesthetic', 'Matching', 'Roleplay'],
    sampleNames: ['Bunny', 'Mochi', 'Cookie', 'Peach', 'Strawberry', 'Lilac', 'Panda', 'Kitten', 'Sugar', 'Honey', 'Blossom', 'Daisy'],
    seoContent: `
      <h2>Creating the Perfect Cute Username</h2>
      <p>Cute usernames are essential for social games like <strong>Adopt Me!</strong> and <strong>Brookhaven RP</strong>. They convey friendliness and approachability.</p>
      <h3>Themes for Cute Names</h3>
      <ul>
        <li><strong>Food & Sweets:</strong> <em>Mochi</em>, <em>Cookie</em>, <em>Boba</em>, <em>Strawberry</em>.</li>
        <li><strong>Animals:</strong> <em>Bunny</em>, <em>Kitty</em>, <em>Panda</em>, <em>Duckling</em>.</li>
        <li><strong>Colors:</strong> <em>Pastel</em>, <em>Pink</em>, <em>Lilac</em>, <em>Peach</em>.</li>
      </ul>
      <h3>Kawaii & Anime Influence</h3>
      <p>Our generator also includes Japanese-inspired terms often used in anime culture, such as <em>Chan</em>, <em>Kun</em>, <em>Senpai</em>, and <em>Chibi</em>. Combine these with your favorite nouns to create a unique identity.</p>
    `
  },
  [NameStyle.FUNNY]: {
    path: '/funny-roblox-names',
    style: NameStyle.FUNNY,
    navLabel: 'Funny',
    emoji: '🤡',
    title: "Funny Roblox Name Generator - Troll Username Ideas",
    subtitle: "Troll, Meme & Alt Account Names",
    description: "Generate hilarious, meme-worthy, and troll usernames for your alt account that are safe for Roblox but guaranteed to get a laugh.",
    relatedTags: ['Funny', 'Alt Accounts', 'Privacy', 'Safety'],
    sampleNames: ['CEOofBacon', 'NoobMaster', 'UrMomHatesLag', 'SoggyWaffle', 'Loading_Brain', 'ProfessionalNoob', 'I_Eat_Dirt', 'GlitchyPotato', 'SpicyNoodle', 'TaxEvader'],
    seoContent: `
      <h2>Funny Names for Alt Accounts</h2>
      <p>Sometimes you just want to have fun. Whether you are trolling in a game or creating a secret alt account, a funny name is a great conversation starter.</p>
      <h3>Types of Funny Usernames</h3>
      <ul>
        <li><strong>"CEO of..." Names:</strong> A popular meme format (e.g., <em>CEOofBacon</em>).</li>
        <li><strong>Self-Deprecating:</strong> Names that imply low skill (e.g., <em>ProfessionalNoob</em>, <em>BadAtGame</em>).</li>
        <li><strong>Food Combinations:</strong> Random food items often result in hilarious names (e.g., <em>SoggyWaffle</em>).</li>
      </ul>
      <p><strong>Warning:</strong> Always ensure your funny name adheres to Roblox's Terms of Service. Our generator filters out inappropriate terms to keep your account safe.</p>
    `
  }
};

// Helper to look up route config by style
export const getRouteByStyle = (style: NameStyle) => Object.values(STYLE_ROUTES).find(r => r.style === style);

// Helper to look up route config by path
export const getRouteByPath = (path: string) => Object.values(STYLE_ROUTES).find(r => r.path === path);
